### ISSUE TITLE
OfflineUtils  

### ISSUE THREAD

**Issue by EPSIII** [Esri/collector-tools#13]
After the download of the CollectorUtils toolbox, the OfflineUtils toolset with the projectZ model is not included.  Only the OnlineUtils toolset is added.

**Comment by apulverizer** [comment]
Hi @EPSIII 

What version of ArcMap/Pro are you using?

**Comment by EPSIII** [comment]
10.3.1 ArcMap

I did get it to work in Pro, so I will go that route

**Comment by apulverizer** [comment]
Okay, vertical transformations were introduced at 10.4 so you would need to use at least 10.4 to use some of the tools/scripts in the `OfflineUtils ` toolset.
