### ISSUE TITLE
Add GNSS Metadata Field (Pro) - Hosted Feature Service Failed

### ISSUE THREAD

**Issue by srkiley** [Esri/collector-tools#16]
I;m getting the error below when trying to run the Add GNSS Metadata Field (Pro) - Hosted Feature Service tool on a feature layer in our ArcGIS Online site:

![image](https://user-images.githubusercontent.com/6555418/29181311-4f36ec70-7dc0-11e7-9851-480d91a8e65c.png)

Start Time: Thursday, August 10, 2017 11:33:36 AM
Running script AddGNSSFieldsPythonAPI...
Failed script AddGNSSFieldsPythonAPI...
Traceback (most recent call last):
  File "C:\ArcGIS\ArcGIS_Desktop_Tools\collector-tools-master\CollectorUtils\add_update_gnss_fields_python_api.py", line 17, in <module>
    from arcgis.gis import GIS
**ImportError: No module named 'arcgis'
Failed to execute (AddGNSSFieldsPythonAPI).**
Failed at Thursday, August 10, 2017 11:33:37 AM (Elapsed Time: 0.88 seconds

**Comment by danmaps** [comment]
Please make sure that you have the ArcGIS API for Python installed. Here are [instructions to do this through ArcGIS Pro](https://developers.arcgis.com/python/guide/install-and-set-up/#Install-using-ArcGIS-Pro).

**Comment by srkiley** [comment]
Thanks @danmaps, That worked. I had this working at the previous version of ArcGIS Pro. I don;t remember adding the Python package, but must have. I apologize for submitting this as an issue. I should have read the documentation closer.
