### ISSUE TITLE
Issue with ProjectZ

### ISSUE THREAD

**Issue by Hughwyn** [Esri/collector-tools#18]
When trying to run ProjectZ, as soon as I pick the input feature I get an ERROR 000816 message

Any ideas would be much appreciated

Thanks 

![image](https://user-images.githubusercontent.com/31462766/30094179-982a63e4-931e-11e7-89e1-923ce6a1251a.png)

![image](https://user-images.githubusercontent.com/31462766/30094168-7a3ef174-931e-11e7-8f1f-07f8b84c2961.png)

**Comment by miaogeng** [comment]
@Hughwyn We have checked in a fix for this issue. You can download latest build
