### ISSUE TITLE
Add GNSS Metadata Fields (Pro) - FeatureClass 

### ISSUE THREAD

**Issue by DCC2017** [Esri/collector-tools#19]
I keep getting a syntax error for both FeatureClass and Hosted Service "Add GNSS Metadata Fields" ... the solution says make sure the script file is in the right location but when I refer to the folder the toolbox is in, there is no script "Add GNSS Metadata Fields (Pro).py" How do I extract that script out so its referencing the proper script or am I missing a step? I am using ArcGIS Pro  2.0.1

**Comment by DCC2017** [comment]
![error](https://user-images.githubusercontent.com/31704042/30124562-61b13df8-92ea-11e7-92da-88a0d7da11bd.jpg)

**Comment by Kevin-GIS** [comment]
Closing this issue for the time being, can reopen if this issue is still reproducible.
