### ISSUE TITLE
Converting GNSS Heights from HAE to MSL

### ISSUE THREAD

**Issue by shildebrand2** [Esri/collector-tools#30]
I'm am curious if these tools can help me out.  I have an esri personal geodatabase (.mdb) of 80,000+ gps records exported from trimble pathfinder office.  These records all have heights exported using HAE (Height Above Ellipsoid).  I need all of the heights in these records converted to MSL (Mean Sea Level).  Can this tool or any other tool out there accomplish this?  The only way i've been able to solve this is to re-export each .cor file that is exported into the .mdb and re-create the .mdb using the new exported tables.

Any help would be greatly appreciated!

Sam Hildebrand

**Comment by miaogeng** [comment]
if Z value of your geometry is  HAE (Height Above Ellipsoid), you can try Project tool in ArcGIS Pro or ArcMap.

**Comment by shildebrand2** [comment]
Do you know how to run this tool within ArcMap?  The Project_Z tool says it only works in ArcGIS Pro, which I don't have access to.
