### ISSUE TITLE
ERROR 000732 While Running Project Z

### ISSUE THREAD

**Issue by TedFrauenfelder** [Esri/collector-tools#33]
I'm attempting to run the Project Z tool in Pro on a set of survey points and I'm running into the following error when the tool reaches the Maintain Attachments script:

> Running script MaintainAttachments...
Enabling Attachments
Enabled Attachments
Copying Attachments..
Failed script Maintain Attachments...
Traceback (most recent call last):
  File "C:\Users\tfrauenfelder\Documents\ArcGIS\Projects\GPS\maintain_attachments.py", line 41, in enable_copy_attachments
    arcpy.Append_management(inputRow, outputTable)
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 3984, in Append
    raise e
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 3981, in Append
    retval = convertArcObjectToPythonObject(gp.Append_management(*gp_fixargs((inputs, target, schema_type, field_mapping, subtype), True)))
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\geoprocessing\_base.py", line 506, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
 ERROR 000732: Input Datasets: Dataset C:\Users\tfrauenfelder\Documents\ArcGIS\Projects\GPS\GPS.gdb\SURVEY__ATTACH does not exist or is not supported
Failed to execute (Append).

These are the setting I am using for conversion in the Project Z tool-
![image](https://user-images.githubusercontent.com/36247014/35945093-99e9cc68-0c24-11e8-8c47-cf7c560b0d1e.png)

Any insight into what is going wrong here would be much appreciated, thanks!

**Comment by Sanikanchi** [comment]
Hi, did you get answer to your problem yet? I have same issue. I would appreciate your reply and any suggestion. Thank you

**Comment by Sanikanchi** [comment]
Thank you so much. It ran successfully when I made it attachment enable.
