### ISSUE TITLE
Having issue finding project Z model 

### ISSUE THREAD

**Issue by ndeliman** [Esri/collector-tools#34]
Currently, I am having an issue finding the project Z model in the tool box. I have esri 10.5 and downloaded the collect tools and extracted to a specified location. When I open up the folder in windows explorer it shows everything in the folder but when opening the folder location in catalog or arc map it doesn't show anything in the CollectorUtils

**Comment by ndeliman** [comment]
Or is there anyway you can send me the model in Arc MAP

**Comment by miaogeng** [comment]
as shown at https://github.com/Esri/collector-tools/tree/master/CollectorUtils, Project Z tool only works in ArcGIS Pro.
