### ISSUE TITLE
Serious Security Issue

### ISSUE THREAD

**Issue by tpcolson** [Esri/collector-tools#36]
Two of the tools call for an AGOL password, however, the password is displayed as plain text and stored in the GP history. This can be changed by setting the parameter to "String (hidden)", but should be default. In addition, this security issue isn't disclosed in the documentation for this tool, and instructions on how to obscure the password should be clearly communicated to tool users.

**Comment by doug-m** [comment]
Appreciate the feedback @tpcolson. We'll make this change shortly.

**Comment by niti5425** [comment]
This issue has been addressed. Closing it.
