### ISSUE TITLE
Geographic Transformation Help

### ISSUE THREAD

**Issue by DennisAllen** [Esri/collector-tools#5]
Thanks for putting together this tool.  It looks like just what I need to accomplish a project I am working on.

I am starting to work with a Trimble R2 centimeter accuracy GPS unit and have paired it with with my android phone using Trimble's GNSS Status App and Collector for ArcGIS.  Through the GNSS Status App I am connecting to an Internet RTK network for real time corrections.

I have used the Add GNSS Metadata Fields tool to begin collecting the GNSS Metadata and that is working very well.

What I am having trouble with is an understanding of how to use the ProjectZ tool.  Particularly, I am having trouble applying the geographic transformation.  I am not sure how to do it correctly.  Can you provide and help with this?

Thanks,
Dennis

**Comment by miaogeng** [comment]
Denise, 

what version of ArcMap or ArcGIS Pro do you use? What are you trying to use this ProjectZ tool for? 

-Morga

**Comment by Kevin-GIS** [comment]
Closing this issue for the time being, can reopen if this issue is still reproducible.
