### ISSUE TITLE
ProjectZ tool not working in ArcPro 2.2

### ISSUE THREAD

**Issue by achen70** [Esri/collector-tools#54]
Hi there,
I am working with a Leica Zeno GG04 GPS unit and have paired it with with my IPad using Leica Zeno Connect App and Beta version of Collector for ArcGIS. Through the Zeno Connect App I am connecting to an Internet RTK network for real time corrections.

I have used the Add GNSS Metadata Fields tool to begin collecting the GNSS Metadata and that is working very well. However, I kept getting error when running the ProjectZ tool, please help me fix this!  Thanks,

Amy
-------------------------------------------------------------------------------------------------------------------**
Parameters
Input Features	C:\Users\chena9\Documents\ArcGIS\Projects\MyProject1\MyProject1.gdb\Export_Output_2_RecreateGeom
Input Coordinate System (of the x, y, z values)	GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],VERTCS['NAD_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PARAMETER['Vertical_Shift',0.0],PARAMETER['Direction',1.0],UNIT['Meter',1.0]]
X-Value Coordinates	ESRIGNSS_LONGITUDE
Y-Value Coordinates	ESRIGNSS_LATITUDE
Z-Value Coordinates	ESRIGNSS_ALTITUDE
Output Dataset or Feature Class	C:\Users\chena9\Documents\ArcGIS\Projects\MyProject1\MyProject1.gdb\monu
Output Coordinate System	GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],VERTCS['NAVD_1988',VDATUM['North_American_Vertical_Datum_1988'],PARAMETER['Vertical_Shift',0.0],PARAMETER['Direction',1.0],UNIT['Meter',1.0]]
Geographic Transformation	NAD_1983_To_NAVD88_CONUS_GEOID12B_Height
 
Messages
Start Time: Monday, July 2, 2018 11:59:14 AM
Executing (Recreate Geometry): RecreateGeometry C:\Users\chena9\Documents\ArcGIS\Projects\MyProject1\MyProject1.gdb\Export_Output_2_RecreateGeom GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],VERTCS['NAD_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PARAMETER['Vertical_Shift',0.0],PARAMETER['Direction',1.0],UNIT['Meter',1.0]] ESRIGNSS_LONGITUDE ESRIGNSS_LATITUDE ESRIGNSS_ALTITUDE C:\Users\chena9\Documents\ArcGIS\Projects\MyProject1\MyProject1.gdb\Export_Output_2_RecreateGeom1
Start Time: Monday, July 2, 2018 11:59:15 AM
Running script Recreate Geometry...
Creating new FC...
Copied data to new FC...
0 record(s) skipped due to empty metdata fields
All Rows Updated..
Completed script Recreate Geometry...
Succeeded at Monday, July 2, 2018 11:59:17 AM (Elapsed Time: 1.80 seconds)
Executing (Project): Project C:\Users\chena9\Documents\ArcGIS\Projects\MyProject1\MyProject1.gdb\Export_Output_2_RecreateGeom1 C:\Users\chena9\Documents\ArcGIS\Projects\MyProject1\MyProject1.gdb\monu GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],VERTCS['NAVD_1988',VDATUM['North_American_Vertical_Datum_1988'],PARAMETER['Vertical_Shift',0.0],PARAMETER['Direction',1.0],UNIT['Meter',1.0]] NAD_1983_To_NAVD88_CONUS_GEOID12B_Height GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],VERTCS['NAD_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PARAMETER['Vertical_Shift',0.0],PARAMETER['Direction',1.0],UNIT['Meter',1.0]] NO_PRESERVE_SHAPE # VERTICAL
Start Time: Monday, July 2, 2018 11:59:17 AM
Succeeded at Monday, July 2, 2018 11:59:18 AM (Elapsed Time: 1.17 seconds)
Executing (Maintain Attachments): MaintainAttachments C:\Users\chena9\Documents\ArcGIS\Projects\MyProject1\MyProject1.gdb\Export_Output_2_RecreateGeom C:\Users\chena9\Documents\ArcGIS\Projects\MyProject1\MyProject1.gdb\monu
Start Time: Monday, July 2, 2018 11:59:19 AM
Running script Maintain Attachments...
Enabling Attachments
Enabled Attachments
Copying Attachments..
Failed script Maintain Attachments...
Traceback (most recent call last):
  File "C:\Python27\collector-tools-master\CollectorUtils\maintain_attachments.py", line 41, in enable_copy_attachments
    arcpy.Append_management(inputRow, outputTable)
  File "c:\users\chena9\appdata\local\programs\arcgis\pro\Resources\arcpy\arcpy\management.py", line 4318, in Append
    raise e
  File "c:\users\chena9\appdata\local\programs\arcgis\pro\Resources\arcpy\arcpy\management.py", line 4315, in Append
    retval = convertArcObjectToPythonObject(gp.Append_management(*gp_fixargs((inputs, target, schema_type, field_mapping, subtype, expression), True)))
  File "c:\users\chena9\appdata\local\programs\arcgis\pro\Resources\arcpy\arcpy\geoprocessing\_base.py", line 496, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
 ERROR 000732: Input Datasets: Dataset C:\Users\chena9\Documents\ArcGIS\Projects\MyProject1\MyProject1.gdb\Export_Output_2_RecreateGeom__ATTACH does not exist or is not supported
Failed to execute (Append).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python27\collector-tools-master\CollectorUtils\maintain_attachments.py", line 58, in <module>
    enable_copy_attachments(args.input_fc, args.output_fc)
  File "C:\Python27\collector-tools-master\CollectorUtils\maintain_attachments.py", line 44, in enable_copy_attachments
    arcpy.Error(e)
AttributeError: module 'arcpy' has no attribute 'Error'
 Failed to execute (Maintain Attachments).
Failed at Monday, July 2, 2018 11:59:21 AM (Elapsed Time: 1.85 seconds)
 Failed to execute (ProjectZ).
Failed at Monday, July 2, 2018 11:59:21 AM (Elapsed Time: 6.69 seconds

**Comment by niti5425** [comment]
@achen70 Does your input feature class have attachments or enabled for attachments?
Also you need python 3+ to run this tool.

**Comment by achen70** [comment]
Hi Nitin,
Thanks for checking my message. The feature class have attachments enabled. I will upgrade python and give it a try.

**Comment by achen70** [comment]
Hi Nitin,
I noticed that I have python 3.6.5 within ArcPro, would you please tell me how to set the projectz ArcTool run with this version instead of 2.7?

Thanks,

Aimei

**Comment by niti5425** [comment]
Hi @achen70, 
We have pushed a fix for this issue in the latest update. Please give it a try.

**Comment by Kevin-GIS** [comment]
Closing this issue for the time being, can reopen if this issue is still reproducible.
