### ISSUE TITLE
SyntaxError line 7

### ISSUE THREAD

**Issue by baumannscs** [Esri/collector-tools#69]
When I attempt to run the tool I get this error:
![add_gnss_metadata](https://user-images.githubusercontent.com/44508793/47585813-6d47a380-d92c-11e8-8217-2b17dac1f455.JPG)

How do I fix this? Thank You!

**Comment by JohnDriz** [comment]
Having the same issue.  Would like to see the answer to this one.

**Comment by Kevin-GIS** [comment]
@JohnDriz 

I just tested this in ArcMap 10.7 with a freshly downloaded zip from this repo and I cannot reproduce this issue.

I tested on a new point feature class in a file geodatabase. 

- What type of layer are you using as the input for that tool?
- What version of ArcMap?
- Did you recently download the tools and extract the toolbox from the zip folder?

Thanks
-Kevin
