### ISSUE TITLE
OfflineUtils tool does not show on ArcGIS 10.3

### ISSUE THREAD

**Issue by moiAK** [Esri/collector-tools#8]
The script tools for OfflineUtils aren't available when opened in ArcGIS 10.3.

![103](https://cloud.githubusercontent.com/assets/1986395/25012588/ea2709a2-203e-11e7-8fb6-216c63ae4360.jpg)

VS.

![104](https://cloud.githubusercontent.com/assets/1986395/25012590/eca67014-203e-11e7-979b-2c554a0fbe7f.jpg)

**Comment by apulverizer** [comment]
Per the [collectorUtils readme](https://github.com/Esri/collector-tools/blob/master/CollectorUtils/README.md)

> If you wish to use the toolbox in a version lower than 10.4, you can rebuild the toolbox in ArcGIS Desktop 10.x by creating a new toolbox, adding a script tool to it, and specifying the required parameters. Details can be seen in the documentation for each tool. Details on building script tools can be found here.

Check out [this link](http://desktop.arcgis.com/en/arcmap/latest/analyze/creating-tools/a-quick-tour-of-creating-tools-in-python.htm) for more details on re-creating the toolbox.

Let me know if  you run into any issues.
