### ISSUE TITLE
Error 000816 The tool is not valid

### ISSUE THREAD

**Issue by tfgenty** [Esri/collector-tools#83]
Would anyone have any idea as to what might be causing an invalid Project Z tool? As soon as I add any feature class to the Input Features parameter, I get the error warning: Error 000816 The tool is not valid.

My feature class has the GNSS fields added to it and I am using ArcGIS Pro 2.5. I also have ArcGIS for Desktop installed with python 2.7, so perhaps that is causing the issue?

Any help would be appreciated!

**Comment by slouque** [comment]
I am getting the same error! Any help on this issue from users who have encountered this?

Thanks!

**Comment by Kevin-GIS** [comment]
@tfgenty and @slouque 

- Is this the first time you've tried using the Project Z tool? Or was it working previously?

- While this shouldn't be causing the problem, just to make sure, have you already installed the Vertical Datum Transformations for ArcGIS Pro?

- Within ArcGIS Pro, can you successfully run any python commands, even from the built-in Python window? Perhaps something simple like `import arcpy`. Just wanting to rule out any general issues with Python. 

- Do you know which version of the Python API you're running. I believe Pro 2.5 comes with 1.7. In Pro > Project > Python > Install Packages > arcgis. 

Regarding:
>I also have ArcGIS for Desktop installed with python 2.7, so perhaps that is causing the issue?

I also have that installed on my machine and it's not causing a problem. Therefore I wouldn't think that should matter in this case. 

Thank you

**Comment by slouque** [comment]
Thanks for the reply!

Yes this is my first time trying to use the Project Z tool and yes I have downloaded the Vertical Datum Transformations as instructed in the online tutorials in  the ESRI community forums.

I recently installed ArcGIS Pro 2.5 so I am assuming Python 1.7 is the version installed with it although I am not able to check at this moment bc I am working from home during the pandemic and ArcGIS Pro is installed on my office computer.

I do have ArcMap 10.7 installed on my computer at the office also.

Thanks for the help on this matter

Scott
________________________________

**Comment by Kevin-GIS** [comment]
Thank you @slouque 

Would you be able to share with me a test copy of a file geodatabase that includes a feature class that can reproduce the issue with on your end? I would just like to see if I can reproduce it on my end.

Thank you

**Comment by slouque** [comment]
Thank you for your reply Kevin,

With everything going on right now with the COVID19 pandemic and having to work from home, all this will be on hold from my end until I can get back to my office where I can access the file geodatabases. Once I am back though I will definitely try to share that geodatabase with you. Just provide me some instructions on how I could upload it to github or if it would be better to share through email.

Thanks for helping me with this,

Scott

________________________________

**Comment by Kevin-GIS** [comment]
Hi @slouque 

No problem at all, I completely understand. 

Either way will work for me, you can upload a zipped file GDB straight to a GitHub comment through drag/drop, it just has to be < 10 mb. Or you can email to me directly at kburke@esri.com.

When you're ready, feel free to go ahead and add a comment or send me an email and we can get things going again. 

Thanks

**Comment by slouque** [comment]
Thanks,

Scott Louque

________________________________

**Comment by slouque** [comment]
Hi Kevin,

This is Scott Louque. I had inquired through Github about the Project Z tool. I am only here for today for a little while and won’t be back until May 4th.

You had asked me to send you the File Geodatabase containing my point feature class. I only collected one point to test it out with the tool

Here it is.

Thank you!

**Comment by Kevin-GIS** [comment]
Thank you @slouque 

I don't see the geodatabase. Was it attached as a zip file? 

Thanks

**Comment by slouque** [comment]
Yes, the file should be in this zip file. At least I can see it on my end.

If it’s not then I can try rezipping it and send again.

Thanks,

Scott Louque
St James Parish GIS Analyst
225-562-2431

**Comment by Kevin-GIS** [comment]
I don't see the zip in the github comment though. Can you try emailing to me? kburke@esri.com

Thanks
-Kevin

**Comment by slouque** [comment]
I will try zipping it up again and email it to you at the email address you sent. I am not in the office today so I will do this once I get back

Thank you!

Scott

________________________________

**Comment by slouque** [comment]
Here is an attached jpg showing the values from the point geodatabse I populated the Project Z tool

Don’t know if this will help you but thought I would send it just so you could see what I was doing.

Thanks,

Scott Louque
St James Parish GIS Analyst
225-562-2431

**Comment by Kevin-GIS** [comment]
Hi @slouque,

I tested with the GDB feature class you emailed me and I am not able to reproduce the issue when adding the input feature class to the Project Z tool. This leads me to believe it's related to the tool environment. I have a few questions:

1. Does this issue only happen with the Project Z tool, or can you also reproduce it with any of the tools within the CollectorUtils_Pro.tbx?

2. When you downloaded the tools from GitHub, were they extracted onto the local machine, as oppose to a network drive?

3. And just to confirm, you can reproduce the issue on your end using the same file gdb and feature class that you emailed me right?

Thank you for that information.
-Kevin

**Comment by slouque** [comment]
Thank you for the reply Kevin.

I just tried adding the point feature class to the Project Z tool in CollectorUtils_Pro toolbox

[cid:image001.png@01D622DA.070F0C90]

And got the same error (000816)

[cid:image002.png@01D622DA.926AB550]

To answer your questions


  1.  The only other tool I have run in the Collector Utils toolbox is Add GNSS Metadata fields which is in the CollectorUtils_ArcMap toolbox and yes I only got that error with the Project Z tool
  2.  No the tools were extracted to a folder on a network drive
  3.  Yes same file I sent you. See above screenshots

Thanks,

Scott Louque
St James Parish GIS Analyst
225-562-2431

**Comment by Kevin-GIS** [comment]
Hi @slouque 

Thank you for that information. 

This is a strange issue, because it doesn't appear to be data related or general to the tool itself, as I cannot reproduce it on my end (at least with the current information)

1. As a test, would it be possible to 1) download a new copy of the tools from https://github.com/Esri/collector-tools 2) extract the contents to the same local machine that Pro is running on 3) then try again with the Project Z tool? (I just want to rule out the network location for that tool specifically)

2. As a test, open the Recreate Geometry tool and input the same feature class. Do you receive the error there? (This is one of the tools that compose the Project Z model)

Thank you.
-Kevin

**Comment by slouque** [comment]
Hi Kevin,

Can you give me some instructions on how to add the collector tools locally?

Do I just copy the Collector Tools Master to my desktop and then access it through ArcGIS Pro or
Should I copy the toolbox directly into the Toolbox location where ArcGIS Pro is installed on my computer

Ie C:/Program Fles/ArcGIS/Resources/Toolbox

Thanks

Scott Louque
St James Parish GIS Analyst
225-562-2431

**Comment by slouque** [comment]
Great news Kevin!

Nvm on the previous email on how to extract the tool.

I just extracted to my desktop and then added the toolbox to my ArcGIS Pro map under the project toolbox and loaded my ElevationPoint file into it and NO error.

When I get a chance to run it, I will get back to you with my results.

Thanks for your help!

Scott Louque
St James Parish GIS Analyst
225-562-2431

**Comment by Kevin-GIS** [comment]
That awesome @slouque!

Thank you for sharing the information. Therefore it sounds like it was due to the network location.

I am not 100% sure why that was still causing an issue, perhaps there was some dependency that could be accessed from the network location by the Project Z tool. 

Please let me know how the tool works for you.

FYI, as you might run into this known error. If you receive an error regarding being unable to locate the attachments table...this is an issue that I am actively working to address. The Project Z tool, being a model, supports another script tool called Maintain Attachments. As the name suggests if the input feature class has existing attachments, they will be preserved in the output feature class. By default that code looks for an attachment table and doesn't play nice when one isn't present. Therefore I am working to make the tool a bit more flexible in this area.

Thanks
-Kevin

**Comment by slouque** [comment]
Kevin,

I went and created a new point feature class, ran the Add GNSS Metadata Fields script on it, added the feature to my web map and then went outside and collected a point with our GNSS receiver.

Exported the feature from my web map into the project geodatabase, then loaded the point feature into the Project Z tool to see if it would work. It didn’t

I got this error

[cid:image001.png@01D623BC.41181750]

Do I need to run the Maintain Attachments script on the feature before I run Project Z?

Thanks,

Scott Louque
St James Parish GIS Analyst
225-562-2431

**Comment by Kevin-GIS** [comment]
Hi @slouque, 

The screenshot of the error message didn't come through in the comment above. Can you please try emailing it to me in a zip or just typing the error message?

Thank you
-Kevin

**Comment by slouque** [comment]
This is the error message

Errors and Warnings

Unable to locate the attachment table for the input feature class.
Failed to execute (Maintain Attachments).
Failed to execute (Project Z)

Thanks

**Comment by Kevin-GIS** [comment]
Thank you @slouque 

Yes that is a known issue I mentioned above. I am working on it. 

As a workaround for now, you can simply enable attachments on your feature class prior to running the Project Z tool. The output feature class will also include attachments, but if you're not working with them, you can disable attachments on the output once done. 

The fix I am working on with support input feature classes that do not have attachments enabled. 

Thanks
-Kevin

**Comment by slouque** [comment]
Thank you Kevin.

I enabled attachments on the feature class and it worked!

Scott Louque
St James Parish GIS Analyst
225-562-2431

**Comment by Kevin-GIS** [comment]
Thank you for that feedback @slouque!

I will close out this issue, but please feel free to create a new issue with any questions or issues you run into.

Thanks
-Kevin

**Comment by slouque** [comment]
Kevin,

What I am trying to obtain with our GNSS receiver is a true elevation value of a point. However, what the z Value the Project Z tool generates for me is not the correct elevation of the points I went collect.

Could this be bc I projected into the wrong coordinate system or is there another step involved in order to get a true elevation value?

Thanks

Scott Louque
St James Parish GIS Analyst
225-562-2431

**Comment by Kevin-GIS** [comment]
Hi @slouque 

For this new question, could you please create a new issue in this repo?

In that new issue, could you please provide the following information:

- What type of GPS receiver are you working with?

- Which OS for Collector are you working with?

- What type of correction service are you using? i.e. RTK from a base station, etc. 

- What is the input spatial reference you're using for the XY and Z? (this should be the spatial reference of the correct service not necessarily the spatial reference for the feature class itself)

- What is the desired output spatial reference for the XY and Z for output feature class?

- When you mentioned `...the z Value the Project Z tool generates for me is not the correct elevation..`, what is the expected Z value?

Thank you for that information
-Kevin

**Comment by slouque** [comment]
Kevin,

I realized right after I sent you the email, all I had to do was reproject the feature class back into the State Plane coordinate system we use over here and then I got an elevation value which is more realistic

So no issue as of now.

Thanks for replying to my question

Scott Louque
St James Parish GIS Analyst
225-562-2431

**Comment by Kevin-GIS** [comment]
Thank you for that information @slouque. Glad the tool is working for you!

Please reach out if you have any questions or issues.

-Kevin

**Comment by slouque** [comment]
Hi Kevin,

I just posted a new issue I had today while entering the output coordinate system for the Project Z tool on the github forum.

Could you please take a look at it and see why I might be getting that warning error

Thanks,

Scott Louque
St James Parish GIS Analyst
225-562-2431
